# Generated by Django 5.0.1 on 2024-01-06 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drfbooks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='publication_year',
            field=models.SmallIntegerField(default=1),
        ),
    ]
